5 acceptance testing
Lexxicus/QnA pull request #3
Opened 2021-02-23 19:13 UTC by Lexxicus

2021-02-25 09:58 UTC, vkurennov requested changes

2021-02-25 09:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'Authorized user' do
у тебя контексты одинаково называются

2021-02-25 09:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'Authorized user' do
и  лучше названия давать что-то вроде "author/non-author", чтобы не запутаться с аутентификацией/авторизацией

2021-02-25 09:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'Authorized user' do
опять же надо более понятное название контекстам дать и они точно не должны быть одинаковыми.

2021-02-25 09:58 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +    scenario 'asks a question' do
у нас же ответ создается, а не вопрос

2021-02-25 09:58 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +      expect(page).to have_content 'Your answer added!!'
нужно проверить, что ответ появился на странице

2021-02-25 09:58 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      expect(page).to have_content question.title
надо проверять не то, что вопрос есть на странице, а то, что ответа больше нет, а перед удалением хорошо бы проверить, что ответ есть на странице

2021-02-25 09:58 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      expect(page).to have_content question.title
теперь поянтно почему тут вопрос, вероятно скопировал аналогичный тест из фичи удаления вопроса ))  в этом нет ничего плохого, только тесты никогда не бывают одинаковыми (иначе какой смысл в одинаковых тестах), а значит, если копируешь, то не забудь поправить не только описание теста, но и его содержимое

2021-02-25 09:58 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
тут перед удалением, хорошо бы проверить, что вопрос есть на странице

2021-02-25 09:58 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на метод проверки автора? любой код, который ты пишешь в каком-либо классе (а модели/контроллеры - это отдельные классы), должен иметь тесты

2021-02-25 16:30 UTC, Lexxicus commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
Мы вроде на страницу вопроса заходим, метод show, или это для того что бы убедиться что текст вопроса на странице вообще отображается?

2021-02-26 11:50 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
да, убедиться, что он есть и что удаление приведет к его исчезновению со страницы

2021-02-26 11:51 UTC, vkurennov approved these changes

2021-02-28 16:51 UTC, merged